import { LatLng } from "./../type/index";
export const sideProfileList = [
  {
    title: "Home",
    link: "/",
  },
  {
    title: "About",
    link: "/about",
  },
  {
    title: "Contact",
    link: "/contact",
  },
  {
    title: "My Page",
    link: "/mypage",
  },
  {
    title: "instagram",
    link: "https://instagram.com",
  },
];

// 33.4707849, 126.4922485; // 엔젤리너스
// 33.4715835, 126.4915281; // 장가네 부엌
// 33.469955, 126.4894937; // 트러스데이
// 33.4720684, 126.4898611; // 광진주택
// 33.4737433, 126.4884714; // 화목원
// 33.47052, 126.4909; // 이름 모를 주차장
// 33.4699443, 126.4887026; // 예쁜 나무 숨겨놈

export const dummyLatLng: LatLng[] = [
  {
    id: 1,
    userEmail: "planzy@planzy.com",
    grd_la: 33.469955,
    grd_lo: 126.4894937,
    latlng: "33.4699550, 126.4894937", // 트러스데이
    title: "트러스데이",
    description: "트러스데이",
    tag: ["실내공원", "온실", "데이트", "커피"],
    address: "제주특별자치도 제주시 오남로 15",
    phone: "064-757-7770",
    time: "10:00 ~ 22:00",
    holiday: "연중무휴",
    homepage: "https://www.instagram.com/trustday_jeju/",
    sns: "https://www.instagram.com/trustday_jeju/",
    img: [
      "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
    ],
    children: [
      {
        id: 1,
        img: "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
        title: "피카츄",
        description: "피카츄",
        distance: "1000",
        tag: ["실내공원", "온실", "데이트", "커피"],
      },
      {
        id: 2,
        img: "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
        title: "파이리",
        description: "파이리",
        distance: "500",
        tag: ["실내공원", "온실", "데이트", "커피"],
      },
      {
        id: 3,
        img: "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
        title: "그랑죠",
        description: "그랑죠",
        distance: "600",
        tag: ["실내공원", "온실", "데이트", "커피"],
      },
    ],
    story: [
      {
        id: 1,
        title: "다육이와 함께하는 하루",
        imageUrl: "/story_1.png",
        tag: ["#깜찍", "#온실", "#데이트", "#커피"],
        duration: 3000,
      },
      {
        id: 2,
        title: "라벤더와 함께하는 하루",
        imageUrl: "/story_2.png",
        tag: ["#깜찍", "#온실", "#데이트", "#커피"],
        duration: 3000,
      },
      {
        id: 3,
        title: "로즈마리와 함께하는 하루",
        imageUrl: "/story_3.png",
        tag: ["#깜찍", "#온실", "#데이트", "#커피"],
        duration: 3000,
      },
    ],
  },
  {
    id: 2,
    userEmail: "planzy@planzy.com",
    grd_la: 33.4700346,
    grd_lo: 126.4932767,
    latlng: "33.4700346, 126.4932767", // 한라 수목원
    title: "한라 수목원",
    description: "한라 수목원",
    tag: ["실내공원", "온실", "데이트", "커피"],
    address: "제주특별자치도 제주시 오남로 15",
    phone: "064-757-7770",
    time: "10:00 ~ 22:00",
    holiday: "연중무휴",
    homepage: "https://www.instagram.com/trustday_jeju/",
    sns: "https://www.instagram.com/trustday_jeju/",
    img: [
      "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
    ],
    children: [
      {
        id: 1,
        img: "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
        title: "피카츄",
        description: "피카츄",
        distance: "1000",
        tag: ["실내공원", "온실", "데이트", "커피"],
      },
      {
        id: 2,
        img: "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
        title: "파이리",
        description: "파이리",
        distance: "500",
        tag: ["실내공원", "온실", "데이트", "커피"],
      },
      {
        id: 3,
        img: "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
        title: "그랑죠",
        description: "그랑죠",
        distance: "600",
        tag: ["실내공원", "온실", "데이트", "커피"],
      },
    ],
    story: [
      {
        id: 1,
        title: "다육이와 함께하는 하루",
        imageUrl: "/story_1.png",
        tag: ["#깜찍", "#온실", "#데이트", "#커피"],
        duration: 3000,
      },
      {
        id: 2,
        title: "라벤더와 함께하는 하루",
        imageUrl: "/story_2.png",
        tag: ["#깜찍", "#온실", "#데이트", "#커피"],
        duration: 3000,
      },
      {
        id: 3,
        title: "로즈마리와 함께하는 하루",
        imageUrl: "/story_3.png",
        tag: ["#깜찍", "#온실", "#데이트", "#커피"],
        duration: 3000,
      },
    ],
  },
  {
    id: 3,
    userEmail: "planzy@planzy.com",
    grd_la: 33.4707849,
    grd_lo: 126.4922485,
    latlng: "33.4707849, 126.4922485", // 엔젤리너스
    title: "엔젤리너스",
    description: "엔젤리너스",
    tag: ["실내공원", "온실", "데이트", "커피"],
    address: "제주특별자치도 제주시 오남로 15",
    phone: "064-757-7770",
    time: "10:00 ~ 22:00",
    holiday: "연중무휴",
    homepage: "https://www.instagram.com/trustday_jeju/",
    sns: "https://www.instagram.com/trustday_jeju/",
    img: [
      "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
    ],
    children: [
      {
        id: 1,
        img: "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
        title: "피카츄",
        description: "피카츄",
        distance: "1000",
        tag: ["실내공원", "온실", "데이트", "커피"],
      },
      {
        id: 2,
        img: "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
        title: "파이리",
        description: "파이리",
        distance: "500",
        tag: ["실내공원", "온실", "데이트", "커피"],
      },
      {
        id: 3,
        img: "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
        title: "그랑죠",
        description: "그랑죠",
        distance: "600",
        tag: ["실내공원", "온실", "데이트", "커피"],
      },
    ],
    story: [
      {
        id: 1,
        title: "다육이와 함께하는 하루",
        imageUrl: "/story_1.png",
        tag: ["#깜찍", "#온실", "#데이트", "#커피"],
        duration: 3000,
      },
      {
        id: 2,
        title: "라벤더와 함께하는 하루",
        imageUrl: "/story_2.png",
        tag: ["#깜찍", "#온실", "#데이트", "#커피"],
        duration: 3000,
      },
      {
        id: 3,
        title: "로즈마리와 함께하는 하루",
        imageUrl: "/story_3.png",
        tag: ["#깜찍", "#온실", "#데이트", "#커피"],
        duration: 3000,
      },
    ],
  },
  {
    id: 4,
    userEmail: "planzy@planzy.com",
    grd_la: 33.4715835,
    grd_lo: 126.4915281,
    latlng: "33.4715835, 126.4915281", // 장가네 부엌
    title: "장가네 부엌",
    description: "장가네 부엌",
    tag: ["실내공원", "온실", "데이트", "커피"],
    address: "제주특별자치도 제주시 오남로 15",
    phone: "064-757-7770",
    time: "10:00 ~ 22:00",
    holiday: "연중무휴",
    homepage: "https://www.instagram.com/trustday_jeju/",
    sns: "https://www.instagram.com/trustday_jeju/",
    img: [
      "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
    ],
    children: [
      {
        id: 1,
        img: "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
        title: "피카츄",
        description: "피카츄",
        distance: "1000",
        tag: ["실내공원", "온실", "데이트", "커피"],
      },
      {
        id: 2,
        img: "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
        title: "파이리",
        description: "파이리",
        distance: "500",
        tag: ["실내공원", "온실", "데이트", "커피"],
      },
      {
        id: 3,
        img: "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
        title: "그랑죠",
        description: "그랑죠",
        distance: "600",
        tag: ["실내공원", "온실", "데이트", "커피"],
      },
    ],
    story: [
      {
        id: 1,
        title: "다육이와 함께하는 하루",
        imageUrl: "/story_1.png",
        tag: ["#깜찍", "#온실", "#데이트", "#커피"],
        duration: 3000,
      },
      {
        id: 2,
        title: "라벤더와 함께하는 하루",
        imageUrl: "/story_2.png",
        tag: ["#깜찍", "#온실", "#데이트", "#커피"],
        duration: 3000,
      },
      {
        id: 3,
        title: "로즈마리와 함께하는 하루",
        imageUrl: "/story_3.png",
        tag: ["#깜찍", "#온실", "#데이트", "#커피"],
        duration: 3000,
      },
    ],
  },
  {
    id: 5,
    userEmail: "planzy2@planzy.com",
    grd_la: 33.4711887,
    grd_lo: 126.4936699,
    latlng: "33.4711887, 126.4936699", //
    title: "여기는 어디게?",
    description: "여기는 어디게?ㅋㅋㅋㅋㅋㅋㅋㅋ",
    tag: ["실내공원", "온실", "데이트", "커피"],
    address: "제주특별자치도 제주시 오남로 15",
    phone: "064-757-7770",
    time: "10:00 ~ 22:00",
    holiday: "연중무휴",
    homepage: "https://www.instagram.com/trustday_jeju/",
    sns: "https://www.instagram.com/trustday_jeju/",
    img: [
      "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
    ],
    children: [
      {
        id: 1,
        img: "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
        title: "피카츄",
        description: "피카츄",
        distance: "1000",
        tag: ["실내공원", "온실", "데이트", "커피"],
      },
      {
        id: 2,
        img: "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
        title: "파이리",
        description: "파이리",
        distance: "500",
        tag: ["실내공원", "온실", "데이트", "커피"],
      },
      {
        id: 3,
        img: "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
        title: "그랑죠",
        description: "그랑죠",
        distance: "600",
        tag: ["실내공원", "온실", "데이트", "커피"],
      },
    ],
    story: [
      {
        id: 1,
        title: "다육이와 함께하는 하루",
        imageUrl: "/story_1.png",
        tag: ["#깜찍", "#온실", "#데이트", "#커피"],
        duration: 3000,
      },
      {
        id: 2,
        title: "라벤더와 함께하는 하루",
        imageUrl: "/story_2.png",
        tag: ["#깜찍", "#온실", "#데이트", "#커피"],
        duration: 3000,
      },
      {
        id: 3,
        title: "로즈마리와 함께하는 하루",
        imageUrl: "/story_3.png",
        tag: ["#깜찍", "#온실", "#데이트", "#커피"],
        duration: 3000,
      },
    ],
  },
  {
    id: 6,
    userEmail: "planzy1@planzy.com",
    grd_la: 33.4720684,
    grd_lo: 126.4898611,
    latlng: "33.4720684, 126.4898611", // 광진주택
    title: "광진주택",
    description: "광진주택이라는 이름에 식물이 가득!",
    tag: ["실내공원", "온실", "데이트", "커피"],
    address: "제주특별자치도 제주시 오남로 15",
    phone: "064-757-7770",
    time: "10:00 ~ 22:00",
    holiday: "연중무휴",
    homepage: "https://www.instagram.com/trustday_jeju/",
    sns: "https://www.instagram.com/trustday_jeju/",
    img: [
      "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
    ],
    children: [
      {
        id: 1,
        img: "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
        title: "피카츄",
        description: "피카츄",
        distance: "1000",
        tag: ["실내공원", "온실", "데이트", "커피"],
      },
      {
        id: 2,
        img: "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
        title: "파이리",
        description: "파이리",
        distance: "500",
        tag: ["실내공원", "온실", "데이트", "커피"],
      },
      {
        id: 3,
        img: "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
        title: "그랑죠",
        description: "그랑죠",
        distance: "600",
        tag: ["실내공원", "온실", "데이트", "커피"],
      },
    ],
    story: [
      {
        id: 1,
        title: "다육이와 함께하는 하루",
        imageUrl: "/story_1.png",
        tag: ["#깜찍", "#온실", "#데이트", "#커피"],
        duration: 3000,
      },
      {
        id: 2,
        title: "라벤더와 함께하는 하루",
        imageUrl: "/story_2.png",
        tag: ["#깜찍", "#온실", "#데이트", "#커피"],
        duration: 3000,
      },
      {
        id: 3,
        title: "로즈마리와 함께하는 하루",
        imageUrl: "/story_3.png",
        tag: ["#깜찍", "#온실", "#데이트", "#커피"],
        duration: 3000,
      },
    ],
  },
  {
    id: 7,
    userEmail: "planzy@planzy.com",
    grd_la: 33.4737433,
    grd_lo: 126.4884714,
    latlng: "33.4737433, 126.4884714", // 화목원
    title: "화목원",
    description: "화목원",
    tag: ["실내공원", "온실", "데이트", "커피"],
    address: "제주특별자치도 제주시 오남로 15",
    phone: "064-757-7770",
    time: "10:00 ~ 22:00",
    holiday: "연중무휴",
    homepage: "https://www.instagram.com/trustday_jeju/",
    sns: "https://www.instagram.com/trustday_jeju/",
    img: [
      "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
    ],
    children: [
      {
        id: 1,
        img: "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
        title: "피카츄",
        description: "피카츄",
        distance: "1000",
        tag: ["실내공원", "온실", "데이트", "커피"],
      },
      {
        id: 2,
        img: "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
        title: "파이리",
        description: "파이리",
        distance: "500",
        tag: ["실내공원", "온실", "데이트", "커피"],
      },
      {
        id: 3,
        img: "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
        title: "그랑죠",
        description: "그랑죠",
        distance: "600",
        tag: ["실내공원", "온실", "데이트", "커피"],
      },
    ],
    story: [
      {
        id: 1,
        title: "다육이와 함께하는 하루",
        imageUrl: "/story_1.png",
        tag: ["#깜찍", "#온실", "#데이트", "#커피"],
        duration: 3000,
      },
      {
        id: 2,
        title: "라벤더와 함께하는 하루",
        imageUrl: "/story_2.png",
        tag: ["#깜찍", "#온실", "#데이트", "#커피"],
        duration: 3000,
      },
      {
        id: 3,
        title: "로즈마리와 함께하는 하루",
        imageUrl: "/story_3.png",
        tag: ["#깜찍", "#온실", "#데이트", "#커피"],
        duration: 3000,
      },
    ],
  },
  {
    id: 8,
    userEmail: "planzy@planzy.com",
    grd_la: 33.47052,
    grd_lo: 126.4909,
    latlng: "33.47052, 126.4909", // 이름 모를 주차장
    title: "이름 모를 주차장",
    description: "주차장이름이 뭐지?",
    tag: ["실내공원", "온실", "데이트", "커피"],
    address: "제주특별자치도 제주시 오남로 15",
    phone: "064-757-7770",
    time: "10:00 ~ 22:00",
    holiday: "연중무휴",
    homepage: "https://www.instagram.com/trustday_jeju/",
    sns: "https://www.instagram.com/trustday_jeju/",
    img: [
      "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
    ],
    children: [
      {
        id: 1,
        img: "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
        title: "피카츄",
        description: "피카츄",
        distance: "1000",
        tag: ["실내공원", "온실", "데이트", "커피"],
      },
      {
        id: 2,
        img: "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
        title: "파이리",
        description: "파이리",
        distance: "500",
        tag: ["실내공원", "온실", "데이트", "커피"],
      },
      {
        id: 3,
        img: "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
        title: "그랑죠",
        description: "그랑죠",
        distance: "600",
        tag: ["실내공원", "온실", "데이트", "커피"],
      },
    ],
    story: [
      {
        id: 1,
        title: "다육이와 함께하는 하루",
        imageUrl: "/story_1.png",
        tag: ["#깜찍", "#온실", "#데이트", "#커피"],
        duration: 3000,
      },
      {
        id: 2,
        title: "라벤더와 함께하는 하루",
        imageUrl: "/story_2.png",
        tag: ["#깜찍", "#온실", "#데이트", "#커피"],
        duration: 3000,
      },
      {
        id: 3,
        title: "로즈마리와 함께하는 하루",
        imageUrl: "/story_3.png",
        tag: ["#깜찍", "#온실", "#데이트", "#커피"],
        duration: 3000,
      },
    ],
  },
  {
    id: 9,
    userEmail: "planzy@planzy.com",
    grd_la: 33.4699443,
    grd_lo: 126.4887026,
    latlng: "33.4699443, 126.4887026", // 예쁜 나무 숨겨놈
    title: "예쁜 나무 숨겨놈",
    description: "나무가 예쁘다.",
    tag: ["실내공원", "온실", "데이트", "커피"],
    address: "제주특별자치도 제주시 오남로 15",
    phone: "064-757-7770",
    time: "10:00 ~ 22:00",
    holiday: "연중무휴",
    homepage: "https://www.instagram.com/trustday_jeju/",
    sns: "https://www.instagram.com/trustday_jeju/",
    img: [
      "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
    ],
    children: [
      {
        id: 1,
        img: "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
        title: "피카츄",
        description: "피카츄",
        distance: "1000",
        tag: ["실내공원", "온실", "데이트", "커피"],
      },
      {
        id: 2,
        img: "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
        title: "파이리",
        description: "파이리",
        distance: "500",
        tag: ["실내공원", "온실", "데이트", "커피"],
      },
      {
        id: 3,
        img: "https://imagedelivery.net/6qzLODAqs2g1LZbVYqtuQw/38cedff9-834b-4e69-3e07-aa5e570fd500/public",
        title: "그랑죠",
        description: "그랑죠",
        distance: "600",
        tag: ["실내공원", "온실", "데이트", "커피"],
      },
    ],
    story: [
      {
        id: 1,
        title: "다육이와 함께하는 하루",
        imageUrl: "/story_1.png",
        tag: ["#깜찍", "#온실", "#데이트", "#커피"],
        duration: 3000,
      },
      {
        id: 2,
        title: "라벤더와 함께하는 하루",
        imageUrl: "/story_2.png",
        tag: ["#깜찍", "#온실", "#데이트", "#커피"],
        duration: 3000,
      },
      {
        id: 3,
        title: "로즈마리와 함께하는 하루",
        imageUrl: "/story_3.png",
        tag: ["#깜찍", "#온실", "#데이트", "#커피"],
        duration: 3000,
      },
    ],
  },
];
